name: generated_bank_list_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  dart_appwrite: ^10.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
